name: gitleaks scanning
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:

      - name: checkout - current repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

#      - name: Gitleaks - current repo
#        uses: gitleaks/gitleaks-action@v2

      - name: checkout - target repo
        if: always()
        uses: actions/checkout@v3
        with:
#         repository: ayumioka/wiki
#         path: ayumioka/wiki
          repository: tagoyellow412/tago-test
          path: tagoyellow412/tago-test

      - name: Gitleaks - all repos
        if: always()
        uses: gitleaks/gitleaks-action@v2
