name: check file content

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      # - name: Git Clone Action
      #   # You may pin to the exact commit or the version.
      #   # uses: sudosubin/git-clone-action@8a93ce24d47782e30077508cccacf8a05a891bae
      #   uses: sudosubin/git-clone-action@v1.0.1
      #   with:
      #     # Repository owner and name. Ex: sudosubin/git-clone-action
      #     repository: ayumioka/wiki # optional, default is ${{ github.repository }}
      #     # Git host platform. Ex: github, gitlab, bitbucket, gitee, or else (git.suckless.org, ...)
      #     #platform: # optional, default is github
      #     # Git branch or tag to checkout.
      #     #ref: # optional
      #     # Relative path from current directory, where to clone.
      #     #path: # optional
      
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          repository: ayumioka/wiki
          path: wiki

      - name: PowerShell Core Action
        shell: pwsh
        run: Get-ChildItem -R | Select-String -Pattern "password", "pwd", "apikey" -List | Select-Object Path
        
