name: check file content

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  target_phrase: "password", "pwd", "apikey"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      - name: Git Clone
        uses: actions/checkout@v3
        with:
          repository: ayumioka/wiki
          path: wiki

      - name: PowerShell Core Action
        shell: pwsh
        run: Get-ChildItem -R | Select-String -Pattern ${{ env.target_phrase }} -List | Select-Object Path
        # run: Get-ChildItem -R | Select-String -Pattern "password", "pwd", "apikey" -List | Select-Object Path
        
